### Classification of Ready BioDegradable by Ada Boost Classifier

In [2]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd

#### Read Bio-degradabale-data.csv data file

In [3]:
df = pd.read_csv('bio-degradabale-data.csv',delimiter=';')
df.head(3)

,3.919,2.6909,0,0.1,0.2,0.3,0.4,31.4,2,0.5,...,0.19,0.20,0.21,2.949,1.591,0.22,7.253,0.23,0.24,RB
0,4.170,2.1144,0,0,0,0,0,30.8,1,1,...,0,0,0,3.315,1.967,0,7.257,0,0,RB
1,3.932,3.2512,0,0,0,0,0,26.7,2,4,...,0,0,1,3.076,2.417,0,7.601,0,0,RB
2,3.000,2.7098,0,0,0,0,0,20.0,0,2,...,0,0,1,3.046,5.000,0,6.690,0,0,RB

In [4]:
df_x = df.iloc[:,0:-1]
df_x

,3.919,2.6909,0,0.1,0.2,0.3,0.4,31.4,2,0.5,...,0.18,0.19,0.20,0.21,2.949,1.591,0.22,7.253,0.23,0.24
0,4.170,2.1144,0,0,0,0,0,30.8,1,1,...,0,0,0,0,3.315,1.967,0,7.257,0,0
1,3.932,3.2512,0,0,0,0,0,26.7,2,4,...,0,0,0,1,3.076,2.417,0,7.601,0,0
2,3.000,2.7098,0,0,0,0,0,20.0,0,2,...,0,0,0,1,3.046,5.000,0,6.690,0,0
3,4.236,3.3944,0,0,0,0,0,29.4,2,4,...,0,0,0,0,3.351,2.405,0,8.003,0,0
4,4.236,3.4286,0,0,0,0,0,28.6,2,4,...,0,0,0,0,3.351,2.556,0,7.904,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,5.431,2.8955,0,0,0,2,0,32.1,4,1,...,2,0,6,1,3.573,2.242,1,8.088,0,0
1050,5.287,3.3732,0,0,9,0,0,35.3,0,9,...,0,0,3,0,3.787,3.083,3,9.278,0,0
1051,4.869,1.7670,0,1,9,0,5,44.4,0,4,...,0,4,13,0,3.848,2.576,5,9.537,1,0
1052,5.158,1.6914,2,0,36,0,9,56.1,0,0,...,0,1,16,0,5.808,2.055,8,11.055,0,1
1053,5.076,2.6588,2,0,0,0,4,54.5,0,0,...,0,2,0,0,4.009,2.206,0,9.130,0,2

In [5]:
df_y = df.iloc[:,-1]
df_y

0        RB
1        RB
2        RB
3        RB
4        RB
       ...
1049    NRB
1050    NRB
1051    NRB
1052    NRB
1053    NRB
Name: RB, Length: 1054, dtype: object

#### Split train test data

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3)

#### Fit by Ada Boost Classifier module

In [7]:
abc = AdaBoostClassifier(n_estimators=50, learning_rate=1)
model = abc.fit(X_train, y_train)

y_pred = model.predict(X_test)

#### Accuracy Measure

In [8]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8296529968454258